### ISSUE TITLE
Caching login?

### ISSUE THREAD

**Issue by jski** [kiraware/paspybin#31]
Hi! I'm starting to use your library for a personal project, and it's very easy to step into, so thanks!

I'm having an issue where I'm exceeding my API limit for logins, as I am using the login for multiple methods based on your example code provided. Can you advise (and ideally, add to the documentation) how to login once at initialization, and then use the cached login for retrieval throughout the rest of my code? I'm not super familiar with what async/await is doing behind the scenes, so some guidance would be useful.

**Comment by kiraware** [comment]
Thank you for your suggestion. I already notice this while testing.

For cache or save the user_key got from login(), please read the updated docs here https://paspybin.readthedocs.io/en/latest/tutorials/#login

**Comment by jski** [comment]
Great thanks for the quick response! I'll keep an eye out for the new version pushed to pypi to support this change and close the issue when I've tested.

**Comment by kiraware** [comment]
I release the v1.0.0, could you please verify it works?

**Comment by jski** [comment]
Hi, it seems to work fine, although I expected the returned `_user_key` to remain the same on each login with same user/password, but it appears to change. Which is totally fine, just not what I had expected. This should solve my issue as I only need to login once on startup. Thanks! Closing this issue.

**Comment by vexra** [comment]
> Hi, it seems to work fine, although I expected the returned `_user_key` to remain the same on each login with same user/password, but it appears to change.

Yes caching the username and password might be a good idea, but what if someone really just want to get the new `_user_key`? and I think it's not the paspybin responsibility to take care of it, it's the user of paspybin who should save the key somewhere else.

Anyway thank you for using this library :)
